version: "3.8"
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb-data:/data/db
    restart: always
    networks:
      - socioverse_network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    restart: always
    networks:
      - socioverse_network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: adwaithathman/socioverse-server:v1.0
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env
    depends_on:
      - mongodb
      - redis
    networks:
      - socioverse_network
    restart: always

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: adwaithathman/socioverse-client:v1.0
    ports:
      - "5173:5173"
    env_file:
      - ./client/.env
    depends_on:
      - server
    networks:
      - socioverse_network

networks:
  socioverse_network:
    driver: bridge
